// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notifications": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Create Notification",
                "parameters": [
                    {
                        "description": "Create Notification",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification_dto.CreateNotificationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    },
    "definitions": {
        "notification_dto.CreateNotificationDto": {
            "type": "object",
            "required": [
                "deviceToken",
                "lineNumber",
                "stopId"
            ],
            "properties": {
                "deviceToken": {
                    "type": "string",
                    "example": "fIuoGe66REq_eyZaN2V8E0"
                },
                "lineNumber": {
                    "type": "string",
                    "example": "199"
                },
                "precedenceMinutes": {
                    "type": "integer",
                    "maximum": 60,
                    "minimum": 1,
                    "example": 10
                },
                "providerName": {
                    "type": "string",
                    "example": "ztm"
                },
                "stopId": {
                    "type": "string",
                    "example": "1461"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
