definitions:
  notification_dto.CreateNotificationDto:
    properties:
      deviceToken:
        example: fIuoGe66REq_eyZaN2V8E0
        type: string
      lineNumber:
        example: "199"
        type: string
      providerName:
        example: ztm
        type: string
      reminderTime:
        example: 10
        maximum: 60
        minimum: 1
        type: integer
      stopId:
        example: "1461"
        type: string
      stopName:
        example: Przymorze Wielkie
        type: string
    required:
    - deviceToken
    - lineNumber
    - stopId
    - stopName
    type: object
info:
  contact: {}
paths:
  /notifications:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Notification
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/notification_dto.CreateNotificationDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create Notification
      tags:
      - notifications
  /ztm/stop/{stopId}:
    get:
      parameters:
      - description: ZTM Stop ID
        in: path
        name: stopId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get ZTM stop with all line numbers
      tags:
      - ztm
swagger: "2.0"
